image: privacybydesign/node_yarn:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
  - node_modules/

stages:
  - test
  - build

before_script:
  - set -euxo pipefail
  - yarn install

bundle:
  stage: build
  artifacts:
    paths:
      - dist/*
  script:
    - yarn build
